### ISSUE TITLE
Persistent error messages and no volume control Sony HT-ZF9

### ISSUE THREAD

**Issue by ojoaosemtil** [kovalev-sergey/homebridge-sony-audio#1] opened 2021-02-14 21:22 UTC
Hello,

I installed the plugin and it shows a lot of errors and I can’t control volume with the remote or any other way.
I can add the device in home app and I can turn on, off and change the inputs, but these error is constant in homebridge.
It keeps appearing almost every second.

I have a Sony HT-ZF9

[14/02/2021, 21:19:46] [Sony Audio Platform] Adding new accessory: HT-ZF9
[14/02/2021, 21:19:46] [Sony Audio Platform] Compatible device found, added: HT-ZF9
[14/02/2021, 21:19:46] HT-ZF9 is running on port 52101.
[14/02/2021, 21:19:46] Please add [HT-ZF9] manually in Home app. Setup Code: 031-45-154
[14/02/2021, 21:19:47] [Sony Audio Platform] Device HT-ZF9 hasn't a notifier notifyExternalTerminalStatus in disabled [{"name":"notifyAvailablePlaybackFunction","version":"1.0"},{"name":"notifyPlayingContentInfo","version":"1.0"}]
[14/02/2021, 21:19:49] [Sony Audio Platform] Error: connect ECONNREFUSED 0.0.0.0:1901
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 1901,
  config: {
    url: 'http://0.0.0.0:1901/index.html',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.1'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/index.html',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '0.0.0.0',
      port: '1901',
      nativeProtocols: [Object],
      pathname: '/index.html'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'GET /index.html HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: 0.0.0.0:1901\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/index.html',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '0.0.0.0',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://0.0.0.0:1901/index.html',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

**Comment by kovalev-sergey** [comment] 2021-02-15 08:21
Hi,
Can't localize the problem yet
Can you run the Homebridge in debug mode and drop the logs here again?

**Comment by ojoaosemtil** [comment] 2021-02-15 11:28
Ok here it is!
Another thing, every time Homebridge shuts down, the input names turn to, for example, "HDMI1" again, even when I named it "Apple TV" in the home app.

[15/02/2021, 11:24:40] [SonyAudio] Adding new accessory: HT-ZF9
[15/02/2021, 11:24:40] [SonyAudio] Compatible device found, added: HT-ZF9
[15/02/2021, 11:24:40] HT-ZF9 is running on port 52101.
[15/02/2021, 11:24:40] Please add [HT-ZF9] manually in Home app. Setup Code: 031-45-154
[15/02/2021, 11:24:40] [SonyAudio] Device HT-ZF9 opened a socked ws://192.168.1.88:10000/sony/system
[15/02/2021, 11:24:40] [SonyAudio] Device HT-ZF9 opened a socked ws://192.168.1.88:10000/sony/avContent
[15/02/2021, 11:24:40] [SonyAudio] Device HT-ZF9 opened a socked ws://192.168.1.88:10000/sony/audio
[15/02/2021, 11:24:40] [SonyAudio] Set Characteristic Active ->  true
[15/02/2021, 11:24:40] [SonyAudio] Device HT-ZF9 received initial message {"result":[{"enabled":[],"disabled":[{"name":"notifyAlexaRegistrationStatus","version":"1.0"},{"name":"notifyPowerStatus","version":"1.0"},{"name":"notifySWUpdateInfo","version":"1.0"},{"name":"notifySettingsUpdate","version":"1.1"},{"name":"notifyStorageStatus","version":"1.1"}]}],"id":1}
[15/02/2021, 11:24:40] [SonyAudio] Device HT-ZF9 sent subscribe message {"method":"switchNotifications","id":2,"params":[{"disabled":[{"name":"notifyAlexaRegistrationStatus","version":"1.0"},{"name":"notifySWUpdateInfo","version":"1.0"},{"name":"notifySettingsUpdate","version":"1.1"},{"name":"notifyStorageStatus","version":"1.1"}],"enabled":[{"name":"notifyPowerStatus","version":"1.0"}]}],"version":"1.0"}
[15/02/2021, 11:24:40] [SonyAudio] Device HT-ZF9 received initial message {"result":[{"enabled":[],"disabled":[{"name":"notifyVolumeInformation","version":"1.0"}]}],"id":1}
[15/02/2021, 11:24:40] [SonyAudio] Device HT-ZF9 sent subscribe message {"method":"switchNotifications","id":2,"params":[{"disabled":[],"enabled":[{"name":"notifyVolumeInformation","version":"1.0"}]}],"version":"1.0"}
[15/02/2021, 11:24:40] [SonyAudio] Device HT-ZF9 received initial message {"result":[{"enabled":[],"disabled":[{"name":"notifyAvailablePlaybackFunction","version":"1.0"},{"name":"notifyPlayingContentInfo","version":"1.0"}]}],"id":1}
[15/02/2021, 11:24:40] [SonyAudio] Device HT-ZF9 hasn't a notifier notifyExternalTerminalStatus in disabled [{"name":"notifyAvailablePlaybackFunction","version":"1.0"},{"name":"notifyPlayingContentInfo","version":"1.0"}]
[15/02/2021, 11:24:40] [SonyAudio] Device HT-ZF9 sent subscribe message {"method":"switchNotifications","id":2,"params":[{"disabled":[{"name":"notifyAvailablePlaybackFunction","version":"1.0"}],"enabled":[{"name":"notifyPlayingContentInfo","version":"1.0"}]}],"version":"1.0"}
[15/02/2021, 11:24:40] [SonyAudio] Device HT-ZF9 received subscription status {"result":[{"enabled":[{"name":"notifyPowerStatus","version":"1.0"}],"disabled":[{"name":"notifyAlexaRegistrationStatus","version":"1.0"},{"name":"notifySWUpdateInfo","version":"1.0"},{"name":"notifySettingsUpdate","version":"1.1"},{"name":"notifyStorageStatus","version":"1.1"}]}],"id":2}
[15/02/2021, 11:24:40] [SonyAudio] Device HT-ZF9 received subscription status {"result":[{"enabled":[{"name":"notifyPlayingContentInfo","version":"1.0"}],"disabled":[{"name":"notifyAvailablePlaybackFunction","version":"1.0"}]}],"id":2}
[15/02/2021, 11:24:40] [SonyAudio] Device HT-ZF9 received subscription status {"result":[{"enabled":[],"disabled":[{"name":"notifyVolumeInformation","version":"1.0"}]}],"id":2}
[15/02/2021, 11:24:40] [SonyAudio] Set Characteristic Mute ->  false
[15/02/2021, 11:24:40] [SonyAudio] Set Characteristic ActiveIdentifier ->  2
[15/02/2021, 11:24:42] [SonyAudio] Error: connect ECONNREFUSED 0.0.0.0:1901
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 1901,
  config: {
    url: 'http://0.0.0.0:1901/index.html',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.1'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/index.html',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '0.0.0.0',
      port: '1901',
      nativeProtocols: [Object],
      pathname: '/index.html'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'GET /index.html HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: 0.0.0.0:1901\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/index.html',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '0.0.0.0',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://0.0.0.0:1901/index.html',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}


And it keeps repeating this error:

[15/02/2021, 11:24:47] [SonyAudio] Error: connect ECONNREFUSED 0.0.0.0:1901
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '0.0.0.0',
  port: 1901,
  config: {
    url: 'http://0.0.0.0:1901/index.html',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.1'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/index.html',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '0.0.0.0',
      port: '1901',
      nativeProtocols: [Object],
      pathname: '/index.html'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      _header: 'GET /index.html HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: 0.0.0.0:1901\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/index.html',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '0.0.0.0',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://0.0.0.0:1901/index.html',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}

**Comment by kovalev-sergey** [comment] 2021-02-15 12:47
Can't find the problem yet.

I published a new release with additional debug logging.
Whenever there is an opportunity, update and send me fresh logs in debug mode.

As for other problems, I will answer after solving with a flood of errors

Thank you for your participation

P.S. What platform is homebridge running on?

**Comment by ojoaosemtil** [comment] 2021-02-15 13:13
Ok, homebridge is running on a Raspberry Pi.
Here are the logs with the new release:

[15/02/2021, 13:07:53] [SonyAudio] Start registering a new device from the description: http://192.168.1.88:54380/MediaRenderer_HT-ZF9.xml
[15/02/2021, 13:07:54] [SonyAudio] Adding new accessory: HT-ZF9
[15/02/2021, 13:07:54] [SonyAudio] Compatible device found, added: HT-ZF9
[15/02/2021, 13:07:54] HT-ZF9 is running on port 52101.
[15/02/2021, 13:07:54] Please add [HT-ZF9] manually in Home app. Setup Code: 031-45-154
[15/02/2021, 13:07:54] [SonyAudio] Device HT-ZF9 opened a socked ws://192.168.1.88:10000/sony/audio
[15/02/2021, 13:07:54] [SonyAudio] Device HT-ZF9 opened a socked ws://192.168.1.88:10000/sony/system
[15/02/2021, 13:07:54] [SonyAudio] Device HT-ZF9 opened a socked ws://192.168.1.88:10000/sony/avContent
[15/02/2021, 13:07:54] [SonyAudio] Set Characteristic Active ->  true
[15/02/2021, 13:07:54] [SonyAudio] Device HT-ZF9 received initial message {"result":[{"enabled":[],"disabled":[{"name":"notifyVolumeInformation","version":"1.0"}]}],"id":1}
[15/02/2021, 13:07:54] [SonyAudio] Device HT-ZF9 sent subscribe message {"method":"switchNotifications","id":2,"params":[{"disabled":[],"enabled":[{"name":"notifyVolumeInformation","version":"1.0"}]}],"version":"1.0"}
[15/02/2021, 13:07:54] [SonyAudio] Device HT-ZF9 received initial message {"result":[{"enabled":[],"disabled":[{"name":"notifyAlexaRegistrationStatus","version":"1.0"},{"name":"notifyPowerStatus","version":"1.0"},{"name":"notifySWUpdateInfo","version":"1.0"},{"name":"notifySettingsUpdate","version":"1.1"},{"name":"notifyStorageStatus","version":"1.1"}]}],"id":1}
[15/02/2021, 13:07:54] [SonyAudio] Device HT-ZF9 sent subscribe message {"method":"switchNotifications","id":2,"params":[{"disabled":[{"name":"notifyAlexaRegistrationStatus","version":"1.0"},{"name":"notifySWUpdateInfo","version":"1.0"},{"name":"notifySettingsUpdate","version":"1.1"},{"name":"notifyStorageStatus","version":"1.1"}],"enabled":[{"name":"notifyPowerStatus","version":"1.0"}]}],"version":"1.0"}
[15/02/2021, 13:07:54] [SonyAudio] Device HT-ZF9 received initial message {"result":[{"enabled":[],"disabled":[{"name":"notifyAvailablePlaybackFunction","version":"1.0"},{"name":"notifyPlayingContentInfo","version":"1.0"}]}],"id":1}
[15/02/2021, 13:07:54] [SonyAudio] Device HT-ZF9 hasn't a notifier notifyExternalTerminalStatus in disabled [{"name":"notifyAvailablePlaybackFunction","version":"1.0"},{"name":"notifyPlayingContentInfo","version":"1.0"}]
[15/02/2021, 13:07:54] [SonyAudio] Device HT-ZF9 sent subscribe message {"method":"switchNotifications","id":2,"params":[{"disabled":[{"name":"notifyAvailablePlaybackFunction","version":"1.0"}],"enabled":[{"name":"notifyPlayingContentInfo","version":"1.0"}]}],"version":"1.0"}
[15/02/2021, 13:07:54] [SonyAudio] Device HT-ZF9 received subscription status {"result":[{"enabled":[],"disabled":[{"name":"notifyVolumeInformation","version":"1.0"}]}],"id":2}
[15/02/2021, 13:07:54] [SonyAudio] Device HT-ZF9 received subscription status {"result":[{"enabled":[{"name":"notifyPowerStatus","version":"1.0"}],"disabled":[{"name":"notifyAlexaRegistrationStatus","version":"1.0"},{"name":"notifySWUpdateInfo","version":"1.0"},{"name":"notifySettingsUpdate","version":"1.1"},{"name":"notifyStorageStatus","version":"1.1"}]}],"id":2}
[15/02/2021, 13:07:54] [SonyAudio] Device HT-ZF9 received subscription status {"result":[{"enabled":[{"name":"notifyPlayingContentInfo","version":"1.0"}],"disabled":[{"name":"notifyAvailablePlaybackFunction","version":"1.0"}]}],"id":2}
[15/02/2021, 13:07:54] [SonyAudio] Set Characteristic Mute ->  false
[15/02/2021, 13:07:54] [SonyAudio] Set Characteristic ActiveIdentifier ->  2
[15/02/2021, 13:07:57] [SonyAudio] Start registering a new device from the description: http://0.0.0.0:1901/index.html
[15/02/2021, 13:07:57] [SonyAudio] Can't retrieve the device description at http://0.0.0.0:1901/index.html: Error: connect ECONNREFUSED 0.0.0.0:1901
[15/02/2021, 13:08:02] [SonyAudio] Start registering a new device from the description: http://0.0.0.0:1901/index.html
[15/02/2021, 13:08:02] [SonyAudio] Can't retrieve the device description at http://0.0.0.0:1901/index.html: Error: connect ECONNREFUSED 0.0.0.0:1901

When changing the volume with the control center remote, nothing happens with the sound bar volume - volume up logs this:

[15/02/2021, 13:11:41] [SonyAudio] Set Characteristic VolumeSelector ->  0
[15/02/2021, 13:11:42] [SonyAudio] Start registering a new device from the description: http://0.0.0.0:1901/index.html
[15/02/2021, 13:11:42] [SonyAudio] Can't retrieve the device description at http://0.0.0.0:1901/index.html: Error: connect ECONNREFUSED 0.0.0.0:1901

Volume down:

[15/02/2021, 13:12:54] [SonyAudio] Set Characteristic VolumeSelector ->  1
[15/02/2021, 13:12:54] [SonyAudio] Set Characteristic Active ->  1
[15/02/2021, 13:12:54] [SonyAudio] Device HT-ZF9: Device API got an error: {"error":[40000,"Request Retry"],"id":55}
[15/02/2021, 13:12:54] [SonyAudio] Set Characteristic Active ->  true
[15/02/2021, 13:12:54] [SonyAudio] Set Characteristic Mute ->  false
[15/02/2021, 13:12:54] [SonyAudio] Set Characteristic ActiveIdentifier ->  2
[15/02/2021, 13:12:57] [SonyAudio] Start registering a new device from the description: http://0.0.0.0:1901/index.html
[15/02/2021, 13:12:57] [SonyAudio] Can't retrieve the device description at http://0.0.0.0:1901/index.html: Error: connect ECONNREFUSED 0.0.0.0:1901

And it continuously show this error:

[15/02/2021, 13:13:02] [SonyAudio] Start registering a new device from the description: http://0.0.0.0:1901/index.html
[15/02/2021, 13:13:02] [SonyAudio] Can't retrieve the device description at http://0.0.0.0:1901/index.html: Error: connect ECONNREFUSED 0.0.0.0:1901
[15/02/2021, 13:13:07] [SonyAudio] Start registering a new device from the description: http://0.0.0.0:1901/index.html
[15/02/2021, 13:13:07] [SonyAudio] Can't retrieve the device description at http://0.0.0.0:1901/index.html: Error: connect ECONNREFUSED 0.0.0.0:1901
[15/02/2021, 13:13:12] [SonyAudio] Start registering a new device from the description: http://0.0.0.0:1901/index.html
[15/02/2021, 13:13:12] [SonyAudio] Can't retrieve the device description at http://0.0.0.0:1901/index.html: Error: connect ECONNREFUSED 0.0.0.0:1901
[15/02/2021, 13:13:17] [SonyAudio] Start registering a new device from the description: http://0.0.0.0:1901/index.html
[15/02/2021, 13:13:17] [SonyAudio] Can't retrieve the device description at http://0.0.0.0:1901/index.html: Error: connect ECONNREFUSED 0.0.0.0:1901
[15/02/2021, 13:13:22] [SonyAudio] Start registering a new device from the description: http://0.0.0.0:1901/index.html
[15/02/2021, 13:13:22] [SonyAudio] Can't retrieve the device description at http://0.0.0.0:1901/index.html: Error: connect ECONNREFUSED 0.0.0.0:1901

**Comment by kovalev-sergey** [comment] 2021-02-15 13:54
Thx,
OK
What I see: your platform (Raspberry) has a process running that responds to discovery requests for SONY devices.

Each device class has a specific header that it responds to. For example, SONY responds to `urn: schemas-sony-com: service: ScalarWebAPI: 1`. For other devices, the header is different and other devices should not respond to requests for other devices.
But some process on your platform (at 0.0.0.0:1901) is responding to this discovery request, which is a violation of the SSDP protocol.

I will make sure that this error does not appear more than once. I cannot completely hide that error, because this may prevent localizing the problems of other users (when, for example, the user has network problems), after all, the problem is in your network environment.

**Comment by ojoaosemtil** [comment] 2021-02-15 14:01
Hm I get it, I’ve used to use the homebridge-Sony-audio-control plugin, I’ve uninstalled it when I installed this plugin, but maybe something is still on the network. Do you have any idea what could be?

So, because of this, I can’t control volume through the control center remote?

**Comment by kovalev-sergey** [comment] 2021-02-15 14:02
> Thank you for the plugin and for your help! :)
No problem and thanks for the help testing and catching bugs  )

After posting a new release of stopping the flood of errors, I close this issue.

Please create new separate tasks for each issue mentioned in the thread. Most likely these are errors on my side )

**Comment by kovalev-sergey** [comment] 2021-02-15 14:04
> So, because of this, I can’t control volume through the control center remote?

No no. Volume is definitely my bug.
And I will need your help to solve it )

**Comment by ojoaosemtil** [comment] 2021-02-15 14:07
Ok! I can help of course!

**Comment by kovalev-sergey** [comment] 2021-02-15 14:13
> I’ve uninstalled it when I installed this plugin, but maybe something is still on the network. Do you have any idea what could be?
I am not familiar with Raspberry but you can google 'how to find which process is using a port'

Look at here https://www.codegrepper.com/code-examples/fortran/kill+running+port+raspberry+pi 
But you have to look for a process for port `1900`

**Comment by kovalev-sergey** [comment] 2021-02-15 16:30
@ojoaosemtil 
Error flooding was stopped at [v1.0.5](https://github.com/kovalev-sergey/homebridge-sony-audio/releases/tag/v1.0.5)

For unanswered questions, create new issues, please

**Closed by kovalev-sergey** 2021-02-15 16:30 UTC
Labels: bug

**Comment by ojoaosemtil** [comment] 2021-07-26 18:52
Hello!
I don’t know if you changed something but in this new release I keep seeing again a lot of messages about the error:
[SonyAudio] Can't retrieve the device description at http://0.0.0.0:1901/index.html: Error: connect ECONNREFUSED 0.0.0.0:1901

Is it possible to keep it like before, warning just once?
Thank u!

**Comment by kovalev-sergey** [comment] 2021-07-27 16:21
Hi @ojoaosemtil 
I fixed it in v1.0.9

**Comment by ojoaosemtil** [comment] 2021-07-27 16:23
Thank u!!

**Comment by kovalev-sergey** [comment] 2021-07-27 16:34
you can confirm that everything is ok?

**Comment by ojoaosemtil** [comment] 2021-07-27 16:35
I’ve just updated and everything seems to be fine! 😊
